using BenchmarkDotNet.Attributes;

namespace CodeWarts.Infrastructure.Implementations.ToCamelCase;

[MemoryDiagnoser]
public class ToCamelCaseBenchmark
{
    [Params(
        "the_super_test_of_interation_andchang_ing_current_index_of_dedicated_sign_and_special_characterthe_super_test_of_interation_andchang_ing_current_index_of_dedicated_sign_and_special_character" +
        "the_super_test_of_interation_andchang_ing_current_index_of_dedicated_sign_and_special_characterthe_super_test_of_interation_andchang_ing_current_index_of_dedicated_sign_and_special_characterthe_super_test_of_interation_andchang_ing_current_index_of_dedicated_sign_and_special_character" +
        "the_super_test_of_interation_andchang_ing_current_index_of_dedicated_sign_and_special_characterthe_super_test_of_interation_andchang_ing_current_index_of_dedicated_sign_and_special_characterthe_super_test_of_interation_andchang_ing_current_index_of_dedicated_sign_and_special_characterthe_super_test_of_interation_andchang_ing_current_index_of_dedicated_sign_and_special_character" +
        "the_super_test_of_interation_andchang_ing_current_index_of_dedicated_sign_and_special_characterthe_super_test_of_interation_andchang_ing_current_index_of_dedicated_sign_and_special_characterthe_super_test_of_interation_andchang_ing_current_index_of_dedicated_sign_and_special_characterthe_super_test_of_interation_andchang_ing_current_index_of_dedicated_sign_and_special_character" +
        "the_super_test_of_interation_andchang_ing_current_index_of_dedicated_sign_and_special_characterthe_super_test_of_interation_andchang_ing_current_index_of_dedicated_sign_and_special_characterthe_super_test_of_interation_andchang_ing_current_index_of_dedicated_sign_and_special_characterthe_super_test_of_interation_andchang_ing_current_index_of_dedicated_sign_and_special_characterthe_super_test_of_interation_andchang_ing_current_index_of_dedicated_sign_and_special_character" +
        "the_super_test_of_interation_andchang_ing_current_index_of_dedicated_sign_and_special_characterthe_super_test_of_interation_andchang_ing_current_index_of_dedicated_sign_and_special_characterthe_super_test_of_interation_andchang_ing_current_index_of_dedicated_sign_and_special_characterthe_super_test_of_interation_andchang_ing_current_index_of_dedicated_sign_and_special_character" +
        "the_super_test_of_interation_andchang_ing_current_index_of_dedicated_sign_and_special_characterthe_super_test_of_interation_andchang_ing_current_index_of_dedicated_sign_and_special_characterthe_super_test_of_interation_andchang_ing_current_index_of_dedicated_sign_and_special_characterthe_super_test_of_interation_andchang_ing_current_index_of_dedicated_sign_and_special_characterthe_super_test_of_interation_andchang_ing_current_index_of_dedicated_sign_and_special_character")]
    public string input;

    [Benchmark]
    public string Execute1() => ToCamelCase.Execute(input);

    [Benchmark]
    public string Execute2() => ToCamelCase.Execute(input);
}